Icons_Of_Excellence = []

Jeff Bezos. $177 B. United States. Amazon. ...

Elon Musk. $151 B. United States. Tesla, SpaceX. ...

Bernard Arnault & family. $150 B. France. LVMH. ...

Bill Gates. $124 B. United States. ...

Mark Zuckerberg. $97 B. United States. ...

Warren Buffett. $96 B. United States. ...

Larry Ellison. $93 B. United States. ...

Larry Page. $91.5 B. United States.



# ItALY