# What is an abandonment schema?
# a bug, solve it, asshole



Individuals who experience some form of disconnection or rejection may develop one or more of these five schemas: abandonment, mistrust/abuse, emotional deprivation, defectiveness/shame, and social isolation.Apr 2, 2020



# I'm just a glitch, a psyco ....
# 
# 
# 
# # professional_deformation
# # maybe is a cool deformation
# 
# 
# 
#  