
link = "https://en.wikipedia.org/wiki/Utilitarianism"


"""
Because utilitarianism is not a single theory, but rather a cluster of related theories that have been developed over two hundred years, criticisms can be made for different reasons and have different targets.

Quantifying utility
A common objection to utilitarianism is the inability to quantify, compare, or measure happiness or well-being. Ray Briggs writes in the Stanford Encyclopedia of Philosophy:[80]

One objection to this interpretation of utility is that there may not be a single good (or indeed any good) which rationality requires us to seek. But if we understand "utility" broadly enough to include all potentially desirable ends—pleasure, knowledge, friendship, health and so on—it's not clear that there is a unique correct way to make the tradeoffs between different goods so that each outcome receives a utility. There may be no good answer to the question of whether the life of an ascetic monk contains more or less good than the life of a happy libertine—but assigning utilities to these options forces us to compare them.

Utility understood this way is a personal preference, in the absence of any objective measurement.

Utility ignores justice
As Rosen (2003) has pointed out, claiming that act utilitarians are not concerned about having rules is to set up a "straw man."[22] Similarly, R.M. Hare refers to "the crude caricature of act utilitarianism which is the only version of it that many philosophers seem to be acquainted with."[81] Given what Bentham says about second order evils,[82] it would be a serious misrepresentation to say that he and similar act utilitarians would be prepared to punish an innocent person for the greater good. Nevertheless, whether they would agree or not, this is what critics of utilitarianism claim is entailed by the theory.

"Sheriff scenario"
A classic version of this criticism was given by H. J. McCloskey in his 1957 "sheriff scenario:"[52]

Suppose that a sheriff were faced with the choice either of framing a Negro for a rape that had aroused hostility to the Negroes (a particular Negro generally being believed to be guilty but whom the sheriff knows not to be guilty)—and thus preventing serious anti-Negro riots which would probably lead to some loss of life and increased hatred of each other by whites and Negroes—or of hunting for the guilty person and thereby allowing the anti-Negro riots to occur, while doing the best he can to combat them. In such a case the sheriff, if he were an extreme utilitarian, would appear to be committed to framing the Negro.

By "extreme" utilitarian, McCloskey is referring to what later came to be called act utilitarianism. He suggests one response might be that the sheriff would not frame the innocent negro because of another rule: "do not punish an innocent person." Another response might be that the riots the sheriff is trying to avoid might have positive utility in the long run by drawing attention to questions of race and resources to help address tensions between the communities.

In a later article, McCloskey says:[83]

Surely the utilitarian must admit that whatever the facts of the matter may be, it is logically possible that an 'unjust' system of punishment—e.g. a system involving collective punishments, retroactive laws and punishments, or punishments of parents and relations of the offender—may be more useful than a 'just' system of punishment?

The Brothers Karamazov
An older form of this argument was presented by Fyodor Dostoyevsky in his book The Brothers Karamazov, in which Ivan challenges his brother Alyosha to answer his question:[84]

Tell me straight out, I call on you—answer me: imagine that you yourself are building the edifice of human destiny with the object of making people happy in the finale, of giving them peace and rest at last, but for that you must inevitably and unavoidably torture just one tiny creature, [one child], and raise your edifice on the foundation of her unrequited tears—would you agree to be the architect on such conditions? ... And can you admit the idea that the people for whom you are building would agree to accept their happiness on the unjustified blood of a tortured child, and having accepted it, to remain forever happy?

Predicting consequences
Some argue that it is impossible to do the calculation that utilitarianism requires because consequences are inherently unknowable. Daniel Dennett describes this as the "Three Mile Island effect".[85] Dennett points out that not only is it impossible to assign a precise utility value to the incident, it is impossible to know whether, ultimately, the near-meltdown that occurred was a good or bad thing. He suggests that it would have been a good thing if plant operators learned lessons that prevented future serious incidents.

Russell Hardin (1990) rejects such arguments. He argues that it is possible to distinguish the moral impulse of utilitarianism (which is "to define the right as good consequences and to motivate people to achieve these") from our ability to correctly apply rational principles that, among other things, "depend on the perceived facts of the case and on the particular moral actor's mental equipment."[86] The fact that the latter is limited and can change does not mean that the former has to be rejected. "If we develop a better system for determining relevant causal relations so that we are able to choose actions that better produce our intended ends, it does not follow that we then must change our ethics. The moral impulse of utilitarianism is constant, but our decisions under it are contingent on our knowledge and scientific understanding."[87]

From the beginning, utilitarianism has recognized that certainty in such matters is unobtainable and both Bentham and Mill said that it was necessary to rely on the tendencies of actions to bring about consequences. G. E. Moore, writing in 1903, said:[88]

We certainly cannot hope directly to compare their effects except within a limited future; and all the arguments, which have ever been used in Ethics, and upon which we commonly act in common life, directed to shewing that one course is superior to another, are (apart from theological dogmas) confined to pointing out such probable immediate advantages ... An ethical law has the nature not of a scientific law but of a scientific prediction: and the latter is always merely probable, although the probability may be very great.

Demandingness objection
Act utilitarianism not only requires everyone to do what they can to maximize utility, but to do so without any favouritism. Mill said, "As between his own happiness and that of others, utilitarianism requires him to be as strictly impartial as a disinterested and benevolent spectator."[89] Critics say that this combination of requirements leads to utilitarianism making unreasonable demands. The well-being of strangers counts just as much as that of friends, family or self. "What makes this requirement so demanding is the gargantuan number of strangers in great need of help and the indefinitely many opportunities to make sacrifices to help them."[90] As Shelly Kagan says, "Given the parameters of the actual world, there is no question that...(maximally)...promoting the good would require a life of hardship, self-denial, and austerity...a life spent promoting the good would be a severe one indeed."[91]

Hooker (2002) describes two aspects to the problem: act utilitarianism requires huge sacrifices from those who are relatively better off and also requires sacrifice of your own good even when the aggregate good will be only slightly increased.[92] Another way of highlighting the complaint is to say that in utilitarianism, "there is no such thing as morally permissible self-sacrifice that goes above and beyond the call of duty."[92] Mill was quite clear about this, "A sacrifice which does not increase, or tend to increase, the sum total of happiness, it considers as wasted."[89]

One response to the problem is to accept its demands. This is the view taken by Peter Singer, who says:[93]

No doubt we do instinctively prefer to help those who are close to us. Few could stand by and watch a child drown; many can ignore the avoidable deaths of children in Africa or India. The question, however, is not what we usually do, but what we ought to do, and it is difficult to see any sound moral justification for the view that distance, or community membership, makes a crucial difference to our obligations.

Others argue that a moral theory that is so contrary to our deeply held moral convictions must either be rejected or modified.[94] There have been various attempts to modify utilitarianism to escape its seemingly over-demanding requirements.[95] One approach is to drop the demand that utility be maximized. In Satisficing Consequentialism, Michael Slote argues for a form of utilitarianism where "an act might qualify as morally right through having good enough consequences, even though better consequences could have been produced."[96] One advantage of such a system is that it would be able to accommodate the notion of supererogatory actions.

Samuel Scheffler takes a different approach and amends the requirement that everyone be treated the same.[97] In particular, Scheffler suggests that there is an "agent-centered prerogative" such that when the overall utility is being calculated it is permitted to count our own interests more heavily than the interests of others. Kagan suggests that such a procedure might be justified on the grounds that "a general requirement to promote the good would lack the motivational underpinning necessary for genuine moral requirements" and, secondly, that personal independence is necessary for the existence of commitments and close personal relations and that "the value of such commitments yields a positive reason for preserving within moral theory at least some moral independence for the personal point of view."[98]

Robert Goodin takes yet another approach and argues that the demandingness objection can be "blunted" by treating utilitarianism as a guide to public policy rather than one of individual morality. He suggests that many of the problems arise under the traditional formulation because the conscientious utilitarian ends up having to make up for the failings of others and so contributing more than their fair share.[99]

Gandjour specifically considers market situations and analyses whether individuals who act in markets may produce a utilitarian optimum. He lists several demanding conditions that need to be satisfied: individuals need to display instrumental rationality, markets need to be perfectly competitive, and income and goods need to be redistributed.[100]

Harsanyi argues that the objection overlooks the fact that "people attach considerable utility to freedom from unduly burdensome moral obligations... most people will prefer a society with a more relaxed moral code, and will feel that such a society will achieve a higher level of average utility—even if adoption of such a moral code should lead to some losses in economic and cultural accomplishments (so long as these losses remain within tolerable limits). This means that utilitarianism, if correctly interpreted, will yield a moral code with a standard of acceptable conduct very much below the level of highest moral perfection, leaving plenty of scope for supererogatory actions exceeding this minimum standard."[101]

Aggregating utility
The objection that "utilitarianism does not take seriously the distinction between persons" came to prominence in 1971 with the publication of John Rawls' A Theory of Justice.[102] The concept is also important in animal rights advocate Richard Ryder's rejection of utilitarianism, in which he talks of the "boundary of the individual," through which neither pain nor pleasure may pass.[103]

However, a similar objection was noted in 1970 by Thomas Nagel, who claimed that consequentialism "treats the desires, needs, satisfactions, and dissatisfactions of distinct persons as if they were the desires, etc., of a mass person;"[104] and even earlier by David Gauthier, who wrote that utilitarianism supposes that "mankind is a super-person, whose greatest satisfaction is the objective of moral action.... But this is absurd. Individuals have wants, not mankind; individuals seek satisfaction, not mankind. A person's satisfaction is not part of any greater satisfaction."[105] Thus, the aggregation of utility becomes futile as both pain and happiness are intrinsic to and inseparable from the consciousness in which they are felt, rendering impossible the task of adding up the various pleasures of multiple individuals.

A response to this criticism is to point out that whilst seeming to resolve some problems it introduces others. Intuitively, there are many cases where people do want to take the numbers involved into account. As Alastair Norcross has said:[106]

[S]uppose that Homer is faced with the painful choice between saving Barney from a burning building or saving both Moe and Apu from the building...it is clearly better for Homer to save the larger number, precisely because it is a larger number.... Can anyone who really considers the matter seriously honestly claim to believe that it is worse that one person die than that the entire sentient population of the universe be severely mutilated? Clearly not.

It may be possible to uphold the distinction between persons whilst still aggregating utility, if it accepted that people can be influenced by empathy.[107] This position is advocated by Iain King,[108] who has suggested the evolutionary basis of empathy means humans can take into account the interests of other individuals, but only on a one-to-one basis, "since we can only imagine ourselves in the mind of one other person at a time."[109] King uses this insight to adapt utilitarianism, and it may help reconcile Bentham's philosophy with deontology and virtue ethics.[110][111][112]

Philosopher John Taurek also argued that the idea of adding happiness or pleasures across persons is quite unintelligible and that the numbers of persons involved in a situation are morally irrelevant.[113] Taurek's basic concern comes down to this: we cannot explain what it means to say that things would be five times worse if five people die than if one person dies. "I cannot give a satisfactory account of the meaning of judgments of this kind," he wrote (p. 304). He argues that each person can only lose one person's happiness or pleasures. There is not five times more loss of happiness or pleasure when five die: who would be feeling this happiness or pleasure? "Each person's potential loss has the same significance to me, only as a loss to that person alone. because, by hypothesis, I have an equal concern for each person involved, I am moved to give each of them an equal chance to be spared his loss" (p. 307). Derek Parfit (1978) and others have criticized Taurek's line,[114][115][116] and it continues to be discussed.[117][118]

Calculating utility is self-defeating
An early criticism, which was addressed by Mill, is that if time is taken to calculate the best course of action it is likely that the opportunity to take the best course of action will already have passed. Mill responded that there had been ample time to calculate the likely effects:[89]

[N]amely, the whole past duration of the human species. During all that time, mankind have been learning by experience the tendencies of actions; on which experience all the prudence, as well as all the morality of life, are dependent...It is a strange notion that the acknowledgment of a first principle is inconsistent with the admission of secondary ones. To inform a traveller respecting the place of his ultimate destination, is not to forbid the use of landmarks and direction-posts on the way. The proposition that happiness is the end and aim of morality, does not mean that no road ought to be laid down to that goal, or that persons going thither should not be advised to take one direction rather than another. Men really ought to leave off talking a kind of nonsense on this subject, which they would neither talk nor listen to on other matters of practical concernment.

More recently, Hardin has made the same point. "It should embarrass philosophers that they have ever taken this objection seriously. Parallel considerations in other realms are dismissed with eminently good sense. Lord Devlin notes, 'if the reasonable man "worked to rule" by perusing to the point of comprehension every form he was handed, the commercial and administrative life of the country would creep to a standstill.'"[87]

It is such considerations that lead even act utilitarians to rely on "rules of thumb", as Smart (1973) has called them.[119]

Special obligations criticism
One of the oldest criticisms of utilitarianism is that it ignores our special obligations. For example, if we were given the choice between saving two random people or our mother, most would choose to save their mothers. According to utilitarianism, such a natural action is immoral. The first to respond to this was an early utilitarian and friend of Jeremy Bentham named William Godwin, who held in his work Enquiry Concerning Political Justice that such personal needs should be disregarded in favour of the greatest good for the greatest number of people. Applying the utilitarian principle "that life ought to be preferred which will be most conducive to the general good" to the choice of saving one of two people, either "the illustrious Archbishop of Cambray" or his chambermaid, he wrote:[120]

Supposing the chambermaid had been my wife, my mother or my benefactor. That would not alter the truth of the proposition. The life of [the Archbishop] would still be more valuable than that of the chambermaid; and justice, pure, unadulterated justice, would still have preferred that which was most valuable.

Criticisms of utilitarian value theory
Utilitarianism's assertion that well-being is the only thing with intrinsic moral value has been attacked by various critics. Karl Marx, in Das Kapital, criticises Bentham's utilitarianism on the grounds that it does not appear to recognise that people have different joys in different socioeconomic contexts:[121]

With the driest naivete he takes the modern shopkeeper, especially the English shopkeeper, as the normal man. Whatever is useful to this queer normal man, and to his world, is absolutely useful. This yard-measure, then, he applies to past, present, and future. The Christian religion, e.g., is "useful," "because it forbids in the name of religion the same faults that the penal code condemns in the name of the law." Artistic criticism is "harmful," because it disturbs worthy people in their enjoyment of Martin Tupper, etc. With such rubbish has the brave fellow, with his motto, "nulla dies sine linea [no day without a line]", piled up mountains of books.

Pope John Paul II, following his personalist philosophy, argued that a danger of utilitarianism is that it tends to make persons, just as much as things, the object of use. "Utilitarianism," he wrote, "is a civilization of production and of use, a civilization of things and not of persons, a civilization in which persons are used in the same way as things are used."[122]

Duty-based criticisms
W. D. Ross, speaking form the perspective of his deontological pluralism, acknowledges that there is a duty to promote the maximum of aggregate good, as utilitarianism demands. But, Ross contends, this is just one besides various other duties, like the duty to keep one's promises or to make amends for wrongful acts, which are ignored by the simplistic and reductive utilitarian outlook.[123]: 19 [124]

Roger Scruton was a deontologist, and believed that utilitarianism did not give duty the place that it needed inside our ethical judgements. He asked us to consider the dilemma of Anna Karenina, who had to choose between her love of Vronsky and her duty towards her husband and her son. Scruton wrote, "Suppose Anna were to reason that it is better to satisfy two healthy young people and frustrate one old one than to satisfy one old person and frustrate two young ones, by a factor of 2.5 to 1: ergo I am leaving. What would we think, then, of her moral seriousness?"[125]

Baby farming
In Innocence and Consequentialism (1996), Jacqueline Laing, a critic of utilitarianism, argues that utilitarianism has insufficient conceptual apparatus to comprehend the very idea of innocence, a feature central to any comprehensive ethical theory.[126] In particular, Peter Singer on her view, cannot without contradicting himself reject baby farming (a thought experiment that involves mass-producing deliberately brain-damaged children for live birth for the greater good of organ harvesting) and at the same time hold on to his "personism" a term coined by Jenny Teichman to describe his fluctuating (and Laing says, irrational and discriminatory) theory of human moral value. His explanation that baby farming undermines attitudes of care and concern for the very young, can be applied to babies and the unborn (both 'non-persons' who may be killed, on his view) and contradicts positions that he adopts elsewhere in his work.
"""