# -*- coding: utf-8 -*-
"""audio_processing_pytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZcQFQJxkzOhva48py4wN0lWSnYPsQNF
"""

# When running this tutorial in Google Colab, install the required packages
# with the following.
!pip install torchaudio librosa boto3